export const QUEUE_STATUS = {
  CHO_KHAM:     "CHO_KHAM",
  DANG_KHAM:    "DANG_KHAM",
  CHO_KET_QUA:  "CHO_KET_QUA",
  CHO_TAI_KHAM: "CHO_TAI_KHAM",
  HOAN_THANH:   "HOAN_THANH",
  SKIPPED:      "SKIPPED",
};

export const STAFF_ROLE = {
  SUPER_ADMIN: "super_admin",
  RECEPTIONIST: "receptionist",
  NURSE: "nurse",
  ADMIN: "admin",
};

export const DEVICE_TYPE = {
  KINGPOS: "KINGPOS",
};

export const ACTIVE_QUEUE_STATUSES = [
  QUEUE_STATUS.CHO_KHAM,
  QUEUE_STATUS.DANG_KHAM,
  QUEUE_STATUS.CHO_KET_QUA,
  QUEUE_STATUS.CHO_TAI_KHAM,
];

export const WAITING_QUEUE_STATUSES = [
  QUEUE_STATUS.CHO_KHAM,
  QUEUE_STATUS.CHO_TAI_KHAM,
];
